import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:share_plus/share_plus.dart';

class DetailLogic extends GetxController {
  // Get data from arguments
  late Map<String, dynamic> equipmentData;

  @override
  void onInit() {
    super.onInit();
    equipmentData = Get.arguments ?? {};
  }

  // Get risk color based on level
  List<Color> getRiskGradient() {
    final riskLevel = equipmentData['riskLevel'] ?? 'Low';
    if (riskLevel == 'Low') {
      return [const Color(0xFFE1BEE7), const Color(0xFFCE93D8)]; // 紫色
    } else if (riskLevel == 'Medium') {
      return [const Color(0xFFF8BBD0), const Color(0xFFF48FB1)]; // 粉色
    } else {
      return [const Color(0xFFFFCCBC), const Color(0xFFFFAB91)]; // 橙色
    }
  }

  // 直接分享设备检测报告
  Future<void> shareReport() async {
    try {
      final equipmentName = equipmentData['equipmentName'] ?? 'Unknown Equipment';
      final date = equipmentData['date'] ?? '';
      final condition = equipmentData['condition'] ?? 0;
      final safety = equipmentData['safety'] ?? 0;
      final riskLevel = equipmentData['riskLevel'] ?? 'Unknown';
      final aiAnalysis = equipmentData['aiAnalysis'] ?? '';
      
      // 构建分享文本
      final shareText = '''
🔧 Equipment Inspection Report

📋 Equipment: $equipmentName
📅 Date: $date
🔍 Condition: $condition%
🛡️ Safety: $safety%
⚠️ Risk Level: $riskLevel

🤖 AI Analysis:
$aiAnalysis

Generated by Senxo Equipment Inspector
      '''.trim();

      // 直接调用原生分享
      await Share.share(
        shareText,
        subject: 'Equipment Inspection Report - $equipmentName',
      );
      
    } catch (e) {
      Get.snackbar(
        'Share Error',
        'Failed to share report: ${e.toString()}',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red.withOpacity(0.8),
        colorText: Colors.white,
      );
    }
  }
}
