// ThingTale Mock Data Aggregator
// Auto-generated by tools/_mock_data/generate_aggregate.sh

import 'thingtale_data_1.dart';
import 'thingtale_data_2.dart';
import 'thingtale_data_3.dart';
import 'thingtale_data_4.dart';
import 'thingtale_data_5.dart';
import 'thingtale_data_6.dart';
import 'thingtale_data_7.dart';
import 'thingtale_data_8.dart';
import 'thingtale_data_9.dart';
import 'thingtale_data_10.dart';
import 'thingtale_data_11.dart';
import 'thingtale_data_12.dart';
import 'thingtale_data_13.dart';
import 'thingtale_data_14.dart';
import 'thingtale_data_15.dart';
import 'thingtale_data_16.dart';
import 'thingtale_data_17.dart';
import 'thingtale_data_18.dart';
import 'thingtale_data_19.dart';
import 'thingtale_data_20.dart';

import '../models/thingtale_item.dart';

/// 所有 ThingTale 模拟数据聚合列表
final List<ThingTaleItem> allThingTaleMockData = [
  thingtale_data_1,
  thingtale_data_2,
  thingtale_data_3,
  thingtale_data_4,
  thingtale_data_5,
  thingtale_data_6,
  thingtale_data_7,
  thingtale_data_8,
  thingtale_data_9,
  thingtale_data_10,
  thingtale_data_11,
  thingtale_data_12,
  thingtale_data_13,
  thingtale_data_14,
  thingtale_data_15,
  thingtale_data_16,
  thingtale_data_17,
  thingtale_data_18,
  thingtale_data_19,
  thingtale_data_20,
];
